# Generated by Django 3.0.6 on 2020-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
